/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "math.check" instead.
 */

#include <check.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "s21_math.h"

#define pi 3.14159265358979323846264338327950288

START_TEST(abs_test) {
  int a = 5;
  ck_assert_int_eq(abs(a), s21_abs(a));
  a = -5;
  ck_assert_int_eq(abs(a), s21_abs(a));
  a = 0;
  ck_assert_int_eq(abs(a), s21_abs(a));
  ck_assert_double_eq(abs((int)INFINITY), s21_abs((int)INFINITY));
  ck_assert_double_eq(abs((int)-INFINITY), s21_abs((int)-INFINITY));
}
END_TEST

START_TEST(acos_test) {
  double a = 0.8578;
  ck_assert_float_eq_tol(acos(a), s21_acos(a), 1E-6);
  a = -0.657;
  ck_assert_float_eq_tol(acos(a), s21_acos(a), 1E-6);
  a = 0;
  ck_assert_float_eq_tol(acos(a), s21_acos(a), 1E-6);
  a = 3.476;
  ck_assert_float_nan(acos(a));
  a = 1.0;
  ck_assert_float_eq_tol(acos(a), s21_acos(a), 1E-6);
  a = -1.0;
  ck_assert_float_eq(acos(a), s21_acos(a));
  ck_assert_float_nan(s21_acos(INFINITY));
  ck_assert_float_nan(s21_acos(-INFINITY));
}
END_TEST

START_TEST(asin_test) {
  double a = -0.23;
  ck_assert_float_eq_tol(asin(a), s21_asin(a), 1E-6);
  a = -0.765;
  ck_assert_float_eq_tol(asin(a), s21_asin(a), 1E-6);
  a = -1;
  ck_assert_float_eq_tol(asin(a), s21_asin(a), 1E-6);
  a = 1;
  ck_assert_float_eq_tol(asin(a), s21_asin(a), 1E-6);
  a = 0;
  ck_assert_float_eq_tol(asin(a), s21_asin(a), 1E-6);
  ck_assert_double_nan(s21_asin(INFINITY));
  ck_assert_double_nan(s21_asin(-INFINITY));
}
END_TEST

START_TEST(atan_test) {
  double a = 1.75;
  ck_assert_float_eq_tol(atan(a), s21_atan(a), 1E-6);
  a = -1.75;
  ck_assert_float_eq_tol(atan(a), s21_atan(a), 1E-6);
  a = 0;
  ck_assert_float_eq_tol(atan(a), s21_atan(a), 1E-6);
  ck_assert_double_eq(atan(INFINITY), s21_atan(INFINITY));
  ck_assert_double_eq(atan(-INFINITY), s21_atan(-INFINITY));
}
END_TEST

START_TEST(ceil_test) {
  double a = 15.1;
  ck_assert_float_eq_tol(ceil(a), s21_ceil(a), 1E-6);
  a = 2.1;
  ck_assert_float_eq_tol(ceil(a), s21_ceil(a), 1E-6);
  a = 0;
  ck_assert_float_eq_tol(ceil(a), s21_ceil(a), 1E-6);
  a = -5.1;
  ck_assert_float_eq_tol(ceil(a), s21_ceil(a), 1E-6);
  a = -15.1;
  ck_assert_float_eq_tol(ceil(a), s21_ceil(a), 1E-6);
  ck_assert_double_eq(ceil(INFINITY), s21_ceil(INFINITY));
  ck_assert_double_eq(ceil(-INFINITY), s21_ceil(-INFINITY));
}
END_TEST

START_TEST(cos_test) {
  double a = 7.8 * pi;
  ck_assert_float_eq_tol(cos(a), s21_cos(a), 1E-6);
  a = 0.8 * pi;
  ck_assert_float_eq_tol(cos(a), s21_cos(a), 1E-6);
  a = -1.2 * pi;
  ck_assert_float_eq_tol(cos(a), s21_cos(a), 1E-6);
  a = -17.8 * pi;
  ck_assert_float_eq_tol(cos(a), s21_cos(a), 1E-6);
  a = 0;
  ck_assert_float_eq_tol(cos(a), s21_cos(a), 1E-6);
  ck_assert_double_nan(s21_cos(INFINITY));
  ck_assert_double_nan(s21_cos(-INFINITY));
}
END_TEST

START_TEST(exp_test) {
  double a = 12.75;
  ck_assert_float_eq_tol(exp(a), s21_exp(a), 1E-6);
  a = -12.75;
  ck_assert_float_eq_tol(exp(a), s21_exp(a), 1E-6);
  a = 0;
  ck_assert_float_eq_tol(exp(a), s21_exp(a), 1E-6);
  ck_assert_double_eq(exp(INFINITY), s21_exp(INFINITY));
  ck_assert_double_eq(exp(-INFINITY), s21_exp(-INFINITY));
}
END_TEST

START_TEST(fabs_test) {
  double a = 12.75;
  ck_assert_float_eq_tol(fabs(a), s21_fabs(a), 1E-6);
  a = 0;
  ck_assert_float_eq_tol(fabs(a), s21_fabs(a), 1E-6);
  a = -12.75;
  ck_assert_float_eq_tol(fabs(a), s21_fabs(a), 1E-6);
  ck_assert_double_eq(fabs(INFINITY), s21_fabs(INFINITY));
  ck_assert_double_eq(fabs(-INFINITY), s21_fabs(-INFINITY));
}
END_TEST

START_TEST(floor_test) {
  double a = 2.4;
  ck_assert_float_eq_tol(floor(a), s21_floor(a), 1E-6);
  a = 24.8;
  ck_assert_float_eq_tol(floor(a), s21_floor(a), 1E-6);
  a = 0;
  ck_assert_float_eq_tol(floor(a), s21_floor(a), 1E-6);
  a = -2.4;
  ck_assert_float_eq_tol(floor(a), s21_floor(a), 1E-6);
  a = -34.78;
  ck_assert_float_eq_tol(floor(a), s21_floor(a), 1E-6);
  ck_assert_double_eq(floor(INFINITY), s21_floor(INFINITY));
  ck_assert_double_eq(floor(-INFINITY), s21_floor(-INFINITY));
}
END_TEST

START_TEST(fmod_test) {
  double x = 3.5;
  double y = 5.6;
  ck_assert_float_eq_tol(fmod(x, y), s21_fmod(x, y), 1E-6);
  x = -3.5;
  y = 5.6;
  ck_assert_float_eq_tol(fmod(x, y), s21_fmod(x, y), 1E-6);
  x = 3.5;
  y = -5.6;
  ck_assert_float_eq_tol(fmod(x, y), s21_fmod(x, y), 1E-6);
  x = -3.5;
  y = -5.6;
  ck_assert_float_eq_tol(fmod(x, y), s21_fmod(x, y), 1E-6);
  x = 0;
  y = 5.6;
  ck_assert_float_eq_tol(fmod(x, y), s21_fmod(x, y), 1E-6);
  x = 3.5;
  y = 0;
  ck_assert_float_nan(s21_fmod(x, y));
  x = 0;
  y = 0;
  ck_assert_float_nan(s21_fmod(x, y));
  x = -3.5;
  y = 0;
  ck_assert_float_nan(s21_fmod(x, y));
  x = 0;
  y = -5.6;
  ck_assert_float_eq_tol(fmod(x, y), s21_fmod(x, y), 1E-6);
  x = 0;
  ck_assert_double_eq_tol(fmod(x, INFINITY), s21_fmod(x, INFINITY), 1E-6);
  x = 0;
  ck_assert_double_eq_tol(fmod(x, -INFINITY), s21_fmod(x, -INFINITY), 1E-6);
  y = 0;
  ck_assert_double_nan(s21_fmod(INFINITY, y));
  y = 0;
  ck_assert_double_nan(s21_fmod(-INFINITY, y));
  x = 3.5;
  ck_assert_double_eq_tol(fmod(x, INFINITY), s21_fmod(x, INFINITY), 1E-6);
  x = 3.5;
  ck_assert_double_eq_tol(fmod(x, -INFINITY), s21_fmod(x, -INFINITY), 1E-6);
  y = 5.6;
  ck_assert_double_nan(s21_fmod(INFINITY, y));
  y = 5.6;
  ck_assert_double_nan(s21_fmod(-INFINITY, y));
  x = -3.5;
  ck_assert_double_eq_tol(fmod(x, INFINITY), s21_fmod(x, INFINITY), 1E-6);
  x = -3.5;
  ck_assert_double_eq_tol(fmod(x, -INFINITY), s21_fmod(x, -INFINITY), 1E-6);
  y = -5.6;
  ck_assert_double_nan(s21_fmod(INFINITY, y));
  y = -5.6;
  ck_assert_double_nan(s21_fmod(-INFINITY, y));
  ck_assert_double_nan(s21_fmod(INFINITY, -INFINITY));
  ck_assert_double_nan(s21_fmod(-INFINITY, -INFINITY));
  ck_assert_double_nan(s21_fmod(-INFINITY, INFINITY));
  ck_assert_double_nan(s21_fmod(INFINITY, INFINITY));
}
END_TEST

START_TEST(log_test) {
  double z = 16.3;
  ck_assert_float_eq_tol(log(z), s21_log(z), 1E-6);
  z = 1667.87;
  ck_assert_float_eq_tol(log(z), s21_log(z), 1E-6);
  z = 0;
  ck_assert_float_eq(log(z), s21_log(z));
  z = -16.3;
  ck_assert_float_nan(s21_log(z));
  ck_assert_double_eq(log(INFINITY), s21_log(INFINITY));
  ck_assert_double_nan(s21_log(-INFINITY));
}
END_TEST

START_TEST(pow_test) {
  double x = 2.9;
  double y = 3.2;
  ck_assert_float_eq_tol(pow(x, y), s21_pow(x, y), 1E-6);
  x = -2.9;
  y = 3.2;
  ck_assert_float_nan(s21_pow(x, y));
  x = 2.9;
  y = -3.2;
  ck_assert_float_eq_tol(pow(x, y), s21_pow(x, y), 1E-6);
  x = -2.9;
  y = -3.2;
  ck_assert_float_nan(s21_pow(x, y));
  x = 0;
  y = 3.2;
  ck_assert_float_eq_tol(pow(x, y), s21_pow(x, y), 1E-6);
  x = 2.9;
  y = 0;
  ck_assert_float_eq_tol(pow(x, y), s21_pow(x, y), 1E-6);
  x = 0;
  y = 0;
  ck_assert_float_eq_tol(pow(x, y), s21_pow(x, y), 1E-6);
  x = -2.9;
  y = 0;
  ck_assert_float_eq_tol(pow(x, y), s21_pow(x, y), 1E-6);
  x = 0;
  y = -3.2;
  ck_assert_float_eq(pow(x, y), s21_pow(x, y));
  x = 0;
  ck_assert_double_eq_tol(pow(x, INFINITY), s21_pow(x, INFINITY), 1E-6);
  x = 0;
  ck_assert_double_eq(pow(x, -INFINITY), s21_pow(x, -INFINITY));
  y = 0;
  ck_assert_double_eq_tol(pow(INFINITY, y), s21_pow(INFINITY, y), 1E-6);
  y = 0;
  ck_assert_double_eq_tol(pow(-INFINITY, y), s21_pow(-INFINITY, y), 1E-6);
  x = 2.9;
  ck_assert_double_eq(pow(x, INFINITY), s21_pow(x, INFINITY));
  x = 2.9;
  ck_assert_double_eq_tol(pow(x, -INFINITY), s21_pow(x, -INFINITY), 1E-6);
  y = 3.2;
  ck_assert_double_eq(pow(INFINITY, y), s21_pow(INFINITY, y));
  y = 3.2;
  ck_assert_double_eq(pow(-INFINITY, y), s21_pow(-INFINITY, y));
  x = -2.9;
  ck_assert_double_eq(pow(x, INFINITY), s21_pow(x, INFINITY));
  x = -2.9;
  ck_assert_double_eq_tol(pow(x, -INFINITY), s21_pow(x, -INFINITY), 1E-6);
  y = -3.2;
  ck_assert_double_eq_tol(pow(INFINITY, y), s21_pow(INFINITY, y), 1E-6);
  y = -3.2;
  ck_assert_double_eq(pow(-INFINITY, y), s21_pow(-INFINITY, y));
  ck_assert_double_eq(pow(INFINITY, INFINITY), s21_pow(INFINITY, INFINITY));
  ck_assert_double_eq(pow(-INFINITY, INFINITY), s21_pow(-INFINITY, INFINITY));
  ck_assert_double_eq(pow(INFINITY, -INFINITY), s21_pow(INFINITY, -INFINITY));
  ck_assert_double_eq(pow(-INFINITY, -INFINITY), s21_pow(-INFINITY, -INFINITY));
}
END_TEST

START_TEST(sin_test) {
  double a = 4.0 * pi;
  ck_assert_float_eq_tol(sin(a), s21_sin(a), 1E-6);
  a = -3.0 * pi;
  ck_assert_float_eq_tol(sin(a), s21_sin(a), 1E-6);
  a = 0;
  ck_assert_float_eq_tol(sin(a), s21_sin(a), 1E-6);
  a = 1.5 * pi;
  ck_assert_float_eq_tol(sin(a), s21_sin(a), 1E-6);
  a = -1.5 * pi;
  ck_assert_float_eq_tol(sin(a), s21_sin(a), 1E-6);
  ck_assert_double_nan(s21_sin(INFINITY));
  ck_assert_double_nan(s21_sin(-INFINITY));
}
END_TEST

START_TEST(sqrt_test) {
  double a = 12.543;
  ck_assert_float_eq_tol(sqrt(a), s21_sqrt(a), 1E-6);
  a = -12.543;
  ck_assert_float_nan(s21_sqrt(a));
  a = 0;
  ck_assert_float_eq_tol(sqrt(a), s21_sqrt(a), 1E-6);
  ck_assert_double_eq(sqrt(INFINITY), s21_sqrt(INFINITY));
  ck_assert_double_nan(s21_sqrt(-INFINITY));
}
END_TEST

START_TEST(tan_test) {
  double a = 4.2 * pi;
  ck_assert_float_eq_tol(tan(a), s21_tan(a), 1E-6);
  a = -1.2 * pi;
  ck_assert_float_eq_tol(tan(a), s21_tan(a), 1E-6);
  a = S21_PI_2;
  ck_assert_float_infinite(s21_tan(a));
  a = -S21_PI_2;
  ck_assert_float_infinite(s21_tan(a));
  a = 0;
  ck_assert_float_eq_tol(tan(a), s21_tan(a), 1E-6);
  ck_assert_double_nan(s21_tan(-INFINITY));
  ck_assert_double_nan(s21_tan(INFINITY));
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, abs_test);
  tcase_add_test(tc1_1, acos_test);
  tcase_add_test(tc1_1, asin_test);
  tcase_add_test(tc1_1, atan_test);
  tcase_add_test(tc1_1, ceil_test);
  tcase_add_test(tc1_1, cos_test);
  tcase_add_test(tc1_1, exp_test);
  tcase_add_test(tc1_1, fabs_test);
  tcase_add_test(tc1_1, floor_test);
  tcase_add_test(tc1_1, fmod_test);
  tcase_add_test(tc1_1, log_test);
  tcase_add_test(tc1_1, pow_test);
  tcase_add_test(tc1_1, sin_test);
  tcase_add_test(tc1_1, sqrt_test);
  tcase_add_test(tc1_1, tan_test);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);
  return nf == 0 ? 0 : 1;
}
